paths:
  public: "public"
groups:
  scripts:
    paths:
      - app/scripts/
      - vendor/
    concat:
      "/assets/scripts/config.js": "app/{components_vendor,scripts,components}/**/config.{js,es6,jsx,coffee}"
      "/assets/scripts/app.js": "app/{components_vendor,components,scripts}/**/*.{js,jsx,coffee,es6}"
      "/assets/scripts/templates.js": "vendor/templates/*.{js,jsx,es6,coffee}"
      "/assets/scripts/vendor.js": "vendor/*.{js,jsx,es6,coffee}"
    copy:
      "/assets/scripts": "vendor/{ie,eevee}/**/*.js"
    order:
      - "es5-shim.min.js"
      - "es5-sham.min.js"
      - "vendor/pokeball.js"
      - "..."
      - "app/components/utils/core/locale/locale.es6"
      - "vendor/templates/templates_vendor.js"
      - "vendor/templates/templates_extend.js"
      - "app/scripts/app.coffee"
  styles:
    paths:
      - app/styles/
    concat:
      "/assets/styles/vendor.css": "vendor/*.{css,scss,sass}"
      "/assets/styles/app.css": "{app/components_vendor/**/{view,module}.{css,scss,sass},app/styles/app.{css,scss,sass},app/styles/icons.scss,app/components/**/{view,module}.{css,scss,sass}}"
    copy:
      "/assets/styles": "{vendor/eevee/*.css,vendor/essage.css}"
    order:
      - "vendor/pokeball.css"
      - "..."
  images:
    paths:
      - app/images/
      - app/components/items/resources/images
      - app/components/common/resources/images
      - app/components/shop/resources/images
      - app/components/settlement/resources/images
      - app/components/design/resources/images
      - app/components/user/resources/images
      - app/components/trade/resources/images
      - app/components/pay/resources/images
      - app/components_vendor/items/resources/images
      - app/components_vendor/common/resources/images
      - app/components_vendor/shop/resources/images
      - app/components_vendor/settlement/resources/images
      - app/components_vendor/design/resources/images
      - app/components_vendor/user/resources/images
      - app/components_vendor/trade/resources/images
      - app/components_vendor/pay/resources/images
    sprite:
      "../app/styles/_icons.scss": "app/{components,components_vendor}/**/images/*.png"
    copy:
      "/assets/images/": "{app/images/**/*.jpg,app/images/other-images/*.*,app/{components_vendor,components}/**/other-images/*.*}"
  views:
    paths:
      - app/views/
      - app/components_vendor/
      - app/components/
    copy:
      "/views": "app/views/**/*.hbs"
      "/components/": "{app/{components_vendor,components}/**/view.hbs,app/{components_vendor,components}/**/{backend_templates,all_templates}/*.hbs}"
    compile:
      "/views": "app/views/**/*.erb"
    context:
      tips: false
      projectName: "feebas"
  templates:
    paths:
      - "app/components/"
    precompile:
      "../vendor/templates/templates_vendor.js": "app/components_vendor/**/{frontend_templates,templates,all_templates}/*.hbs"
      "../vendor/templates/templates_extend.js": "{app/views/**/templates/*.hbs,app/components/**/{frontend_templates,templates,all_templates}/*.hbs}"
  files:
    paths:
      - "app/files"
    copy:
      "/": "app/files/{front_mappings,front_href,render_config,acl}.yaml"
    concat:
      "/front_config.yaml": "app/{files,components_vendor,components}/**/front_config.yaml"
      "/back_config.yaml": "app/{files,components_vendor,components}/**/back_config.yaml"
      "/resources/all_mix/zh_CN.yaml": "app/{{components_vendor,components}/**/zh_CN.yaml,files/resources/all_mix/zh_CN.yaml}"
      "/resources/all_mix/en_US.yaml": "app/{{components_vendor,components}/**/en_US.yaml,files/resources/all_mix/en_US.yaml}"
    order:
      - "app/files/front_config.yaml"
      - "app/files/back_config.yaml"
      - "app/components_vendor/common/resources/front_config.yaml"
      - "app/components_vendor/items/resources/front_config.yaml"
      - "app/components_vendor/user/resources/front_config.yaml"
      - "app/components_vendor/design/resources/front_config.yaml"
      - "app/components_vendor/eevee/resources/front_config.yaml"
      - "app/components_vendor/settlement/resources/front_config.yaml"
      - "app/components_vendor/shop/resources/front_config.yaml"
      - "app/components_vendor/pay/resources/front_config.yaml"
      - "app/components_vendor/system/resources/front_config.yaml"
      - "app/components_vendor/trade/resources/front_config.yaml"
      - "app/components_vendor/common/resources/back_config.yaml"
      - "app/components_vendor/items/resources/back_config.yaml"
      - "app/components_vendor/user/resources/back_config.yaml"
      - "app/components_vendor/design/resources/back_config.yaml"
      - "app/components_vendor/eevee/resources/back_config.yaml"
      - "app/components_vendor/settlement/resources/back_config.yaml"
      - "app/components_vendor/shop/resources/back_config.yaml"
      - "app/components_vendor/pay/resources/back_config.yaml"
      - "app/components_vendor/system/resources/back_config.yaml"
      - "app/components_vendor/trade/resources/back_config.yaml"
      - "..."
modules:
  wrapper: "cmd"
  ignored: "vendor/**/*"
  definition: "/assets/scripts/app.js"
sprites:
  selector: ".icon-"
  path: "/assets/images/"
  url: "/feebas/assets/images/"
revision:
  prefix: "/feebas"
  manifest: "manifest.yml"
  files:
    - /views/layout.hbs
    - /views/no_layout.hbs
    - /views/seller/chart_layout.hbs
    - /views/eevee/editor.hbs
    - /views/eevee/wysiwyg.hbs
environments:
  staging:
    groups:
      views:
        context:
          tips: false
notification: true
bundles:
  "pokeball.js":
    version: "master"
    url: "http://registry.terminus.io/packages/pokeball/2.0.1/pokeball.js"
  "pokeball.css":
    version: "master"
    url: "http://registry.terminus.io/packages/pokeball/2.0.1/pokeball.css"
  "jquery.placeholder.js":
    version: "2.0.8"
    url: http://cdn.staticfile.org/jquery-placeholder/2.0.8/jquery.placeholder.js
  "../app/styles/pokeball/_variables.scss":
    version: master
    url: http://registry.terminus.io/packages/theme/2.0.1/pokeball.scss
  eevee/eevee.js:
    version: master
    url: http://registry.terminus.io/packages/eevee/galaxy/eevee.js
  eevee/eevee.css:
    version: master
    url: http://registry.terminus.io/packages/eevee/master/eevee.css
  eevee/eevee-layout.css:
    version: master
    url: http://registry.terminus.io/packages/eevee/master/eevee-layout.css
  eevee/eevee-editable.css:
    version: master
    url: http://registry.terminus.io/packages/eevee/master/eevee-editable.css
  eevee/essage.css:
    version: 0.1.0
    url: http://registry.terminus.io/packages/essage/0.1.0/essage.css
  essage.js:
    version: 0.1.0
    url: http://registry.terminus.io/packages/essage/0.1.0/essage.js
  "ie/html5shiv.js":
    version: 3.7.2
    url: "http://cdn.staticfile.org/html5shiv/3.7.2/html5shiv.js"
  jquery.lazyload.js:
    version: 1.9.3
    url: http://registry.terminus.io/packages/jquery.lazyload.js/1.9.3/jquery.lazyload.js
  wysihtml-toolbar.min.js:
    version: 0.3.0
    url: http://cdn.bootcss.com/wysihtml5/0.3.0/wysihtml5.min.js
  advanced.js:
    version: 0.5.2
    url: http://registry.terminus.io/packages/wysihtml5/0.5.2/wysihtml5-advanced.js
  es5-shim.min.js:
    version: "4.5.4"
    url: http://cdn.bootcss.com/es5-shim/4.5.4/es5-shim.min.js
  es5-sham.min.js:
    version: "4.5.4"
    url: http://cdn.bootcss.com/es5-shim/4.5.4/es5-sham.min.js
  copy-to-clipboard.js:
    version: 3.0.2
    url: http://registry.aixforce.com/packages/copy-to-clipboard/3.0.2/copy-to-clipboard.js
  i18n.js:
    version: 3.0.0.rc11
    url: http://registry.terminus.io/packages/i18n/3.0.0.rc11/i18n.js
  "../app/components_vendor":
    version: master
    url: http://registry.terminus.io/packages/parana-front-base/1.0.0/components.tar.gz
