"search/material_search":
  category: "admin"
  name: "材料查询"
  service: pagingMaterialSearch

"search/material_details":
  category: "ADMIN"
  name: "材料详情"
  service: getMaterialDetailsById

"search/bids_search/common":
  category: "ADMIN"
  name: "获取最近招标项目"
  service: getRecentlyBids

"search/bids_search/condition_search":
  category: "ADMIN"
  name: "招标搜索"
  service: pagingBidsSearch

"search/bids_details":
  category: "ADMIN"
  name: "查询招标详情"
  service: getBidsDetailsAndPorjects
  services:
    _COMPANY_: getDeveloperInfoById

"search/supplier_search":
  category: "ADMIN"
  name: "查询供应商"
  service: searchSupplierList

"search/developer_search":
  category: "ADMIN"
  name: "查询开发商"
  service: searchDeveloperList

"search/company_search_index":
  category: "ADMIN"
  name: "查询公司首页"
  service: searchCompanyList
