"list/provisional_sum":
  category: "admin"
  name: "暂列金"
  service: billSheetItem

"list/provisional_material":
  category: "admin"
  name: "材料暂估价"
  service: billSheetItem

"list/provisional_major":
  category: "admin"
  name: "专业暂估价"
  service: billSheetItem

"list/total_fee":
  category: "admin"
  name: "总承包服务费"
  service: billSheetItem

"list/day_work":
  category: "admin"
  name: "计日工"
  service: billSheetItem

"list/other_fee":
  category: "admin"
  name: "其他费用"
  service: billSheetItem

"list/supplementary":
  category: "admin"
  name: "增补清单"
  service: billSheetItem

"list/instructions":
  category: "admin"
  name: "总说明页"
  service: billGeneralPageInfo
