login:
  type: 'http'
  url: "/api/user/login"
  query:
    - key: username
    - key: password
getUserById:
  type: 'http'
  url: "/api/user/{userId}"
getRolesByUserId:
  type: 'http'
  url: "/api/user/{userId}/roles"

getListPrepare:
  type: http
  method: GET
  url: /api/bill/{bidId}/prepare
  query:
    - key: bidId
    - key: billId

getListSidebar:
  type: http
  method: GET
  url: /api/bill-sheets/{billId}
  query:
    - key: billId
