"seller/sidebar":
  category: "ADMIN"
  name: "商家中心侧边栏"
  service: ""

"user/sidebar":
  category: "ADMIN"
  name: "菜单列表"

"common/ceiling":
  category: "OFFICIAL"
  name: "吊顶"
  service: ""
"common/header":
  category: "OFFICIAL"
  name: "搜索框"
  service: ""

"list/config":
  category: ""
  name: "前台编制清单配置"
  service: "getListPrepare"

list/sidebar:
  name: "编制清单侧边栏页签"
  service: "getListSidebar"
