pagingSubCompanyUser:
  type: http
  method: GET
  url: /api/company/sub/paging
  query:
    - key: userId
    - key: mobile
    - key: status
    - key: pageNo
    - key: pageSize
sellerRolePaging:
  type: http
  method: GET
  url: /api/company/role/paging
  query:
    - key: id
    - key: status
    - key: pageNo
    - key: pageSize
findByIdForUpdate:
  type: http
  method: GET
  url: /api/company/role/find-for-edit
  query:
    - key: id
listShopSites:
  type: SPRING
  uri: io.terminus.galaxy.web.design.service.EcpSiteService:listShopSites
findShopByLoginUser:
  type: http
  method: GET
  url: /api/shop/my-shop
findDeliveryFee:
  method: GET
  type: http
  url: /api/company/paging-delivery-fee-template-detail
  query:
    - key: pageNo
    - key: pageSize
findActivityTool:
  method: GET
  type: http
  url: /api/company/promotion-def/valid
findActivities:
  method: GET
  type: http
  url: /api/company/promotion/paging
  query:
    - key: name
    - key: type
    - key: promotionDefId
    - key: status
    - key: pageNo
    - key: pageSize
findPromotionById:
  method: GET
  type: http
  url: /api/company/promotion/find-for-edit
  query:
    - key: promotionId

