"user/merchant_settled": # component path
  category: "ADMIN" # category: OFFICIAL, TEMPLATE, SHOP, ITEM, ITEM_TEMPLATE
  name: "买家入驻"
  service: "findSellerByLoginUser" # app:serviceKey

"user/address_manage":
  category: "ADMIN"
  name: "买家收货地址管理"
  service: "findValidTradeInfoByBaseUser"

"user/invoice_manage":
  category: "ADMIN"
  name: "买家发票信息管理"
  service: "findInvoiceByLoginUser"

"user/profile":
  category: "ADMIN"
  name: "用户资料"
  service: "findProfileByUser"

"user/bind_email":
  category: "ADMIN"
  name: "用户绑定邮箱"
  service: "findProfileByUser"

"user/register":
  category: "OFFICIAL"
  name: "注册"
  service: ""

"user/register_success":
  category: "OFFICIAL"
  name: "注册成功"
  service: ""

"user/vat_manage":
  category: "ADMIN"
  name: "用户管理增值税发票信息"
  service: "getUserVatByUser"

"user/verify_fail":
  category: "ADMIN"
  name: "邮箱验证失败"
  service: ""
"user/coupons":
  category: "ADMIN"
  name: "我的优惠券"
  service: "pagingCoupon"

"user/header_sidebar":
  category: "ADMIN"
  name: "未读消息"
  service: ""
  services:
    _TOTAL_: "getUnReadMessage"
    _COMPANY_: "getCompanyLists"

"user/my_company":
  category: "ADMIN"
  name: "加入的公司"
  service: "getCompanyInvites"

"user/my_company_review":
  category: "ADMIN"
  name: "待审核的申请"
  service: "getApplyCompany"

"user/login_log":
  category: "ADMIN"
  name: "登录日志"
  service: "getLoginLogPaging"

"user/operate_log":
  category: "ADMIN"
  name: "操作日志"
  service: "getLoginLogPaging"

"user/register_result":
  category: "ADMIN"
  name: "审核公司不通过数据"
  service: "getCompanyNotAgree"


