login:
  type: 'http'
  url: "/api/user/login"
  query:
    - key: username
    - key: password
getUserById:
  type: 'http'
  url: "/api/user/{userId}"
getRolesByUserId:
  type: 'http'
  url: "/api/user/{userId}/roles"
