pagingProjectList:
  type: http
  method: GET
  url: /api/projects
  query:
    - key: id:projectId
    - key: name
    - key: provinceId
    - key: cityId
    - key: status
    - key: type
    - key: pageNo
    - key: pageSize

findProjectById:
  type: http
  method: GET
  url: /api/projects/{id}/detail

pagingSubCompanyUser:
  type: http
  method: GET
  url: /api/company/sub/paging
  query:
    - key: userId
    - key: mobile
    - key: status
    - key: pageNo
    - key: pageSize

pagingUserApply:
  type: http
  method: GET
  url: /api/company/apply/user
  query:
    - key: pageNo
    - key: pageSize

waitAuditCount:
  type: http
  method: GET
  url: /api/company/apply/count

subCompanyRolePaging:
  type: http
  method: GET
  url: /api/company/role/paging
  query:
    - key: id
    - key: status
    - key: pageNo
    - key: pageSize

findByIdForUpdate:
  type: http
  method: GET
  url: /api/company/role/find-for-edit
  query:
    - key: id

findCompanyDetail:
  type: http
  method: GET
  url: /api/company/developer/info

findCompanyApply:
  type: http
  method: GET
  url: /api/company/apply/recent/developer-info

pagingBidsList:
  type: http
  method: GET
  url: /api/bids/index/searchBids
  query:
    - key: projectId
    - key: projectName
    - key: bidName
    - key: speciality1
    - key: speciality2
    - key: bidStatus
    - key: bidType
    - key: pageNo
    - key: pageSize

findProjectName:
  type: http
  method: GET
  url: /api/projects/names

getDefaultProjectInfo:
  type: http
  method: GET
  url: /api/bids/default
  query:
    - key: projectId

getBidsDetails:
  type: http
  method: GET
  url: /api/bids/{bidId}

pagingSupplierList:
  type: http
  url: "/api/supplier/manage/index/search"
  query:
    - key: supplierName
    - key: ra_range
    - key: state
    - key: specialId
    - key: supplierState
    - key: pageNo
    - key: pageSize
    - key: fromdb
    - key: upd

getSpecialTree:
  type: http
  url: "/api/base-major/tree"

getImportSupplier:
  type: 'http'
  url: "/api/supplier/import/views"
  query:
    - key: supplierName
    - key: contactName
    - key: state
    - key: pageNo
    - key: pageSize

getSupplierDetail:
  type: 'http'
  url: "/api/supplier/manage/import/details"
  query:
    - key: supplierId

pagingBidSuppliers:
  type: http
  url: /api/bid/suppliers/paging
  query:
    - key: bidId
    - key: pageSize
    - key: pageNo

getSupplierList:
  type: http
  url: /api/bid/suppliers
  query:
    - key: bidId
    - key: status

getBidsRecords:
  type: http
  url: /api/issued/bid
  query:
    - key: bidId

getAnswersRecords:
  type: http
  url: /api/questions/history
  query:
    - key: bidId

getCompanyDetail:
  type: http
  url: /api/company/supplier/info
  query:
    - key: companyId

getBidsFiles:
  type: http
  url: /api/bids/{bidId}/bidFiles

getSupplyFileDetails:
  type: http
  url: /api/issued/{issuedId}/bid/detail

getAnswerFileDetails:
  type: http
  url: /api/questions/{answerId}/detail

pagingSupplierQuestions:
  type: http
  url: /api/questions/paging
  query:
    - key: pageSize
    - key: pageNo
    - key: answerLogId:answerId

getBidsStatusBar:
  type: http
  url: /api/bids/{bidId}/statusBar

getCompanyUsers:
  type: http
  url: /api/company/sub/list

getFilesByBidIdAndStatus:
  type: http
  url: /api/bids/{bidId}/files/connect
  query:
    - key: type
    - key: connectId

getBidsClarifyDetails:
  type: http
  url: /api/bids/{bidId}/suppliers/{bidSupplierId}/clarify/reply

getBidsOpenedLogs:
  type: http
  url: /api/bids/{bidId}/openedLogs

getBidsStatusById:
  type: http
  url: /api/bids/{bidId}/openedBidInfo

listApprovalFlows:
  type: http
  url: /api/company/approval/flows

getApprovalDetailsById:
  type: http
  url: /api/company/approval/flows/{id}

getApprovalLogsByBid:
  type: http
  url: /api/bids/{connectId}/approveInfo
  query:
    - key: type

getSpecialitiesByBid:
  type: http
  url: /api/bids/{bidId}/specialities

getDeveloperCounts:
  type: http
  url: /api/bids/developer/home/counts

pagingIndexMessage:
  type: http
  url: /api/message/paging
  query:
  - key: pageNo
  - key: pageSize
  - key: startDate
  - key: endDate
  - key: msgRead
  - key: topic

findSupplierDetail:
  type: http
  url: /api/company/supplier/info
  query:
  - key: companyId

getSupplierLibraryDeveloper:
  type: http
  url: /api/supplier/manage/developerViews
  query:
    - key: pageNo
    - key: pageSize
    - key: supplierId:companyId

getSupplierState:
  type: http
  url: /api/supplier/manage/storage/{companyId}

pagingIndexApprovalWaiting:
  type: http
  url: /api/bids/developer/home/approver/flows
  query:
    - key: statusStr
    - key: pageSize
    - key: pageNo
    - key: approveTheme
    - key: endDate
    - key: startDate

pagingIndexApprovalOwner:
  type: http
  url: /api/bids/developer/home/owner/flows
  query:
    - key: disabledStatusStr
    - key: statusStr
    - key: pageSize
    - key: pageNo
    - key: approveTheme
    - key: endDate
    - key: startDate

getInventoryByStatusAndId:
  type: http
  url: /api/bids/{bidId}/files/inventories
  query:
    - key: bidId
    - key: type
    - key: connectId
