"developer/project/project_list":
  category: "ADMIN"
  name: "项目列表"
  service: pagingProjectList

"developer/project/project_edit":
  category: "ADMIN"
  name: "项目编辑"
  service: findProjectById

"developer/project/project_details":
  category: "ADMIN"
  name: "项目详情"
  service: findProjectById

"developer/company/company_info":
  category: "ADMIN"
  name: "公司详情"
  service: findCompanyDetail
  services:
    _APPLY_: findCompanyApply

"developer/company/company_detail":
  category: "ADMIN"
  name: "公司详情"
  service: findCompanyDetail

"developer/company/company_apply":
  category: "ADMIN"
  name: "用户审核"
  service: pagingUserApply
  services:
    _WTOTAL_: waitAuditCount

"developer/accounts":
  category: "ADMIN"
  name: "商家子账号管理"
  service: pagingSubCompanyUser
  services:
    _WTOTAL_: waitAuditCount

"developer/auth":
  category: "ADMIN"
  name: "角色管理"
  service: "subCompanyRolePaging"
  services:
    _WTOTAL_: waitAuditCount

"developer/auth_create":
  category: "ADMIN"
  name: "创建角色"
  service: "findByIdForUpdate"

"developer/bids/bids_manage/bids_list":
  category: "ADMIN"
  name: "招标管理"
  service: pagingBidsList
  services:
    _PROJECTS_: findProjectName
    _COMPANY_USER_: getCompanyUsers

"developer/bids/bids_manage/bids_create":
  category: "ADMIN"
  name: "创建招标立项"
  service: findProjectName
  services:
    _COMPANY_USER_: getCompanyUsers

"developer/bids/bids_manage/bids_edit":
  category: "ADMIN"
  name: "编辑招标立项"
  service: getBidsDetails
  services:
    _COMPANY_USER_: getCompanyUsers

"developer/bids/bids_set":
  category: "ADMIN"
  name: "招标立项"
  service: getBidsDetails

"developer/supplier_manage/supplier_list":
  category: "admin"
  name: "导入供应商列表"
  service: "getImportSupplier"

"developer/supplier_manage/supplier_library":
  category: "admin"
  name: "供应商库列表"
  service: "pagingSupplierList"
  services:
    _TREE_: "getSpecialTree"

"developer/supplier_manage/supplier_collect":
  category: "admin"
  name: "待考察供应商列表"
  service: "pagingSupplierList"
  services:
    _TREE_: "getSpecialTree"

"developer/supplier_manage/supplier_import":
  category: "admin"
  name: "供应商详情"
  service: "getSupplierDetail"

"developer/bids/supplier_select/register":
  category: "ADMIN"
  name: "运营商报名列表"
  service: pagingBidSuppliers

"developer/bids/supplier_select/common":
  category: "ADMIN"
  name: "获取标状态"
  service: getBidsDetails

"developer/bids/supplier_select/waiting":
  category: "ADMIN"
  name: "待入围供应商列表"
  service: getSupplierList
  services:
    _MAJORS_: getSpecialitiesByBid

"developer/bids/publish_answer/common":
  category: "ADMIN"
  name: "发表设置"
  service: getBidsRecords
  services:
    _ANSWERS_: getAnswersRecords
    _COMPANY_USER_: getCompanyUsers

"developer/supplier_manage/supplier_detail":
  category: "ADMIN"
  name: "供应商详情"
  service: getCompanyDetail

"developer/bids/bids_file/common":
  category: "ADMIN"
  name: "招标清单编制"
  service: getBidsFiles
  services:
    _BIDS_: getBidsDetails

"developer/bids/bids_file/operator":
  category: "ADMIN"
  name: "文件经办人"
  service: getCompanyUsers

"developer/bids/publish_answer/supply_details":
  category: "ADMIN"
  name: "补充文件详情"
  service: getSupplyFileDetails

"developer/bids/publish_answer/answer_details":
  category: "ADMIN"
  name: "答疑详情"
  service: getAnswerFileDetails
  services:
   _QUESTIONS_: pagingSupplierQuestions

"developer/bids/bids_open/common":
  category: "ADMIN"
  name: "开标日志"
  service: getBidsOpenedLogs
  services:
    _BIDS_: getBidsStatusById

"developer/bids/bids_open/supplier_list":
  category: "ADMIN"
  name: "入围供应商列表"
  service: getSupplierList

"developer/progress":
  category: "ADMIN"
  name: "招标导航栏"
  service: getBidsStatusBar

"developer/bids/bids_evaluate/supplier_list":
  category: "ADMIN"
  name: "入围供应商列表"
  service: getSupplierList

"developer/bids/bids_evaluate/common":
  category: "ADMIN"
  name: "评标"
  service: getFilesByBidIdAndStatus
  services:
    _BIDS_DETAILS_: getBidsDetails

"developer/bids/bids_evaluate/clarify_details":
  category: "ADMIN"
  name: "澄清详情"
  service: getBidsClarifyDetails

"developer/bids/bids_evaluate/clarify_list":
  category: "ADMIN"
  name: "澄清列表"
  service: getInventoryByStatusAndId

"developer/bids/bids_confirm/supplier_list":
  category: "ADMIN"
  name: "回标供应商"
  service: getSupplierList

"developer/bids/bids_confirm/confirm_info":
  category: "ADMIN"
  name: "定标信息"
  service: getSupplierList
  services:
    _FILES_: getFilesByBidIdAndStatus

"developer/bids/bids_confirm/common":
  category: "ADMIN"
  name: "评标内容"
  service: getFilesByBidIdAndStatus
  services:
    _BIDS_DETAILS_: getBidsDetails

"developer/company/approval_manage/list":
  category: "ADMIN"
  name: "流程配置"
  service: listApprovalFlows

"developer/company/approval_manage/edit":
  category: "ADMIN"
  name: "审批流程详情"
  service: getApprovalDetailsById

"developer/company/approval_manage/common":
  category: "ADMIN"
  name: "获取公司员工"
  service: getCompanyUsers
  services:
    _PROJECTS_: findProjectName
    _APPROVALS_: listApprovalFlows

"developer/bids/bids_approval/log":
  category: "ADMIN"
  name: "获取审批日志"
  service: getApprovalLogsByBid

"developer/index/count":
  category: "ADMIN"
  name: "查询统计"
  service: getDeveloperCounts

"developer/index/message":
  category: "ADMIN"
  name: "主页消息"
  service: pagingIndexMessage

"developer/index/approval":
  category: "ADMIN"
  name: "待我审批"
  service: pagingIndexApprovalWaiting

"developer/index/owner":
  category: "ADMIN"
  name: "我发起的审批"
  service: pagingIndexApprovalOwner

"developer/supplier_manage/supplier_detail":
  category: "ADMIN"
  name: "供应商详情页"
  service: findSupplierDetail
  services:
    _EXTRA_: getSupplierLibraryDeveloper
    _STATE_: getSupplierState

